project:
  type: website

website:
  title: "Siqi Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Example_analysis.qmd
        text: Example_analysis

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

